config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'ajax_test#top'
  post 'ajax_test/update', to: 'ajax_test#update', as: 'ajax_test_update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/ajax_test_controller.rb
class AjaxTestController < ApplicationController
  def top

  end

  def update
    post_text = params[:data][:text]
    results = { :message => post_text}
    render partial: 'ajax_partial', locals: { :results => results }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/ajax_test_helper.rb
module AjaxTestHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ajax_test/_ajax_partial.html.erb
Callback Msg = <%= results[:message] %>

app/views/ajax_test/top.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <div id="request_ajax_update">
      <%= form_tag(ajax_test_update_path, method: :post, remote: true) {%>
        <%= text_field :data, :text %>
        <%= submit_tag 'Post AJAX' %>
      <% } %>
    </div>

    <hr>
    <div id="updated_by_ajax">
      DEFAULT
    </div>
    <hr>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>